<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Silahkan masuk</name>
   <tag></tag>
   <elementGuidId>d279ac7f-1782-4726-b268-835070197cc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='buttonGoInTrack']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonGoInTrack</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d97e8b97-0495-4e53-ba27-821e03b02295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonGoInTrack</value>
      <webElementGuid>ebb01721-52fa-4634-9fe8-7f59f0400bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login</value>
      <webElementGuid>fc3d4b45-6278-4203-864c-2768897061da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan
                                        Masuk</value>
      <webElementGuid>51d3ca47-a2c2-4a8f-a2f8-8f9b7f991660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonGoInTrack&quot;)</value>
      <webElementGuid>a5a76e1d-6402-4770-9ecc-7a3cb419f9ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='buttonGoInTrack']</value>
      <webElementGuid>2891adf9-5da0-4e3f-8dd0-ba294d9b79fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Silahkan
                                        Masuk')]</value>
      <webElementGuid>64a748d9-17e0-460c-9acd-ff274e69ed2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About CODING.ID'])[1]/preceding::a[1]</value>
      <webElementGuid>f6cb82af-0896-43ff-a4e5-b07ef6efb69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Map'])[1]/preceding::a[1]</value>
      <webElementGuid>7191f8f4-fd45-49bc-80b2-7ba7844d1bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/login')])[5]</value>
      <webElementGuid>7c28a2c9-246c-4a31-94bd-d5b12fdbbe61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/a</value>
      <webElementGuid>695499b0-bb27-4848-b76f-de0189fbfcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'buttonGoInTrack' and @href = '/login' and (text() = 'Silahkan
                                        Masuk' or . = 'Silahkan
                                        Masuk')]</value>
      <webElementGuid>aeafb45f-f299-45cf-8062-83a7c13be1c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
